name: Awesome CI

on: [push]

jobs:
  build: # any name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Building the gradle application
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test # run it without testing

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Unit testing
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew test