name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: .
        run: ./gradlew build -x test

      - name: Run tests
        working-directory: .
        run: ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Docker Compose
        working-directory: .
        run: docker-compose up -d --build

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Bring server down
        working-directory: .
        run: docker-compose down